export const LOGIN = "LOGIN";

export const APP_LOAD = "APP_LOAD";
export const REDIRECT = "REDIRECT";
export const REDIRECT_TO = "REDIRECT_TO";
export const ASYNC_START = "ASYNC_START";
export const ASYNC_END = "ASYNC_END";

export const TOGGLE_MODAL = "TOGGLE_MODAL";

export const LOGIN_PAGE_LOADED = "LOGIN_PAGE_LOADED";
export const LOGIN_PAGE_UNLOADED = "LOGIN_PAGE_UNLOADED";
export const SIGN_OUT = "SIGN_OUT";

export const EVENTS_PAGE_LOADED = "EVENTS_PAGE_LOADED";
export const EVENTS_PAGE_UNLOADED = "EVENTS_PAGE_UNLOADED";

export const EVENT_PAGE_LOADED = "EVENT_PAGE_LOADED";
export const EVENT_PAGE_UNLOADED = "EVENT_PAGE_UNLOADED";

export const CREATE_EVENT_MODAL_LOADED = "CREATE_EVENT_MODAL_LOADED";
export const CREATE_EVENT_MODAL_UNLOADED = "CREATE_EVENT_MODAL_UNLOADED";

export const CREATE_MOODLE_MODAL_LOADED = "CREATE_MOODLE_MODAL_LOADED";
export const CREATE_MOODLE_MODAL_UNLOADED = "CREATE_MOODLE_MODAL_UNLOADED";

export const CREATE_EVENT = "CREATE_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";

export const UPDATE_EVENT_VALUE = "UPDATE_EVENT_VALUE";
export const UPDATE_EVENT_INVITE_GUEST = "UPDATE_EVENT_INVITE_GUEST";
export const UPDATE_EVENT_REMOVE_GUEST = "UPDATE_EVENT_REMOVE_GUEST";
